### ISSUE TITLE
Wrong width value for the logo image inside the Auth0LockWidget component

### ISSUE THREAD

**Issue by willamesoares** [Chingu-cohorts/devgaido#124]
I noticed the value set for the `width` attribute in the `auth0-lock-header-logo` class is allowing it to spawn beyond the wrapper boundaries, as shown in the image below.

![logo-before](
http://www.clipular.com/c/5735981054689280.png?k=Dt9ZHwRdHlSsapQtdGulhj4bMK4)

By setting the `width` to `100%` the logo lies entirely inside the wrapper block, as shown below.

![logo-after](http://www.clipular.com/c/6506194134106112.png?k=kYqcug_x0gqarmzjVP6j8iM8fBw)

I checked the file `style.styl` and noticed that the value suggested to this class width is already being set. However, in production, it seems that this value is not being applied.

```
.auth0-lock-header-logo
  width 100% !important
```

**Comment by jdmedlock** [comment]
Thanks @willamesoares! We'll look into this and will include a fix in the next release

**Comment by jdmedlock** [comment]
Issue is suspected to be due to classes in the Auth0 component not being whitelisted so they are skipped by CSS Purify, which prunes unneeded CSS elements from the bundle. Research and corrective action is underway.

**Comment by jdmedlock** [comment]
Resolved by whitelisting Auth0 CSS classes in webpack.config.js that we've overridden in devGaido. Will be promoted to Production at next release.
