### ISSUE TITLE
Filtering controls overlays content in Courses screen and has inconsistent layout

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#15]
**_Error:_** 
The lefthand filtering controls on the Courses screen overlays page content and has an inconsistent format. 

**_Symptoms:_**
1. The filtering controls are always displayed and as a result always overlay page content. Namely, the course cards.
2. As you scroll down it appears that there are two filtering control sections, one overlaying the other on the lefthand side of the screen.

**_Steps to Recreate:_** 
From the Home screen select 'Courses' from the navigation bar (righthand hamburger menu) and scroll up and down to see how the filtering controls appear on the screen.

**_Resolution:_**

**Comment by kimkwanka** [comment]
No longer applies due to changes in App structure.
