### ISSUE TITLE
Progress breadcrumbs are inconsistently applied to pages across the app

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#18]
**_Error:_** 
Progress breadcrumbs are inconsistently applied to pages across the application or are not present at all on some pages.

**_Symptoms:_**
Compare the progress breadcrumbs at the bottom of the Profile screen against other screens. Note that other screens don't have them and the breadcrumbs on the Profile screen don't reflect what will be in the MVP version of the app.

**_Steps to Recreate:_** 
View the bottom of each screen to see where breadcrumbs are missing or where they are incorrect (Profile page).

**_Resolution:_** 
Interim resolution:
1. Remove breadcrumbs from screen
2. Still need to address the once MVP app flow is better defined. Need to examine if and where breadcrumbs are applicable.

**Comment by kimkwanka** [comment]
Breadcrumbs were removed from Profile screen.
