### ISSUE TITLE
Refactor and rename LearningPath Component

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#22]
**_Error:_** 
The component LearningPath.jsx component is shared by both Paths.jsx and CourseCatalog.jsx to format Lessons cards. Since this component is not really a Learning Path, but rather, a Lesson it should be renamed accordingly and reviewed to see if any side effects can result from the fact that it is shared.

**_Symptoms:_**
N/a

**_Steps to Recreate:_** 
N/a

**_Resolution:_**

**Comment by kimkwanka** [comment]
Created new "Card" base component.
