### ISSUE TITLE
Lock icon doesn't change after logging in

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#25]
**_Error:_** 
After logging in the lock menu at the top righthand part of the screen doesn't change. It should change from the unlocked icon to the locked icon.

**_Symptoms:_**
After logging in the lock menu at the top righthand part of the screen doesn't change. 

**_Steps to Recreate:_** 
Log on and off by clicking on the lock icon at the top of the screen, each time noting the fact that the icon doesn't change.

**_Resolution:_** 
Implemented in MVP as a generic avatar.

**Comment by Kornil** [comment]
Should the icon change to an open lock or should it display the username?

I think usually the most accepted way to do it is to display the username and a small avatar if available.

**Comment by jdmedlock** [comment]
I think we need to look at whether this icon and the hamburger menu are both required at the same time. I’m of the opinion that only the lock icon shows until the user logs on. After authentication is confirmed it’s replaced by the hamburger menu whose last entry is ‘Log out’. I do agree that having an avatar is a good idea and it should replace the hamburger icon.
