### ISSUE TITLE
Change TOGGLE_PATH action name in Paths component to TOGGLE_CORE_PATH

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#27]
**_Error:_** 
The TOGGLE_PATH action name is to generic. We currently have only Core Paths, but in the future we will also have User Paths. In anticipation of this TOGGLE_PATH should be changed to TOGGLE_CORE_PATH.

Defer this issue until User Path functionality is added to the app.

**_Symptoms:_**
N/a

**_Steps to Recreate:_** 
N/a

**_Resolution:_**

**Comment by kimkwanka** [comment]
No longer applicable due to removal of Paths page.
