### ISSUE TITLE
Auth0 client secret, etc. are hard coded (and visible to everyone!) on the client side.

### ISSUE THREAD

**Issue by kimkwanka** [Chingu-cohorts/devgaido#29]
Since using .env is not possible (afaik) on the client side we might have to think of a way to deal with this issue. Maybe when we get around to fix the application size issue (https://github.com/Chingu-cohorts/devgaido/issues/13) by creating a custom auth0 widget/page we can have the server provide those details in request.body or something.

**Comment by jdmedlock** [comment]
Resolved by placing in Redux store
