### ISSUE TITLE
Path cards on the Paths screen aren't separated by whitespace

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#31]
**_Issue:_** 
On the Paths screen cards aren't properly separated by whitespace.

**_Symptoms:_**
Some Path cards on the Paths screen have no separation between the left and right edge of two adjacent cards, which makes it appear as though they are joined together. 

**_Steps to Recreate:_** 
Navigate to the Paths screen using the 'Go to Paths" button and examine the layout. In the first row the second and third card have no adequate separation.

**_Resolution:_**

**Comment by kimkwanka** [comment]
No longer applicable due to removal of Paths page.
