### ISSUE TITLE
On the Paths screen Path cards have no separation between the edge of the card and the edge of the screen

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#32]
**_Issue:_** 
The left and right most edge of the left and right most Path card in a row on the Paths screen is laid out directly against the left and right part of the displayable window.

**_Symptoms:_**
The left and right most edge of the left and right most Path card in a row on the Paths screen directly abuts the left and right edge of the window with no separating whitespace.

**_Steps to Recreate:_** 
Using the Paths option on the Navigation Bar go to the Paths screen and examine the way path cards are laid out on the scree.

**_Resolution:_**

**Comment by kimkwanka** [comment]
No longer applicable since Paths page was removed.
