### ISSUE TITLE
Explore button on Paths card returns to Home screen

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#33]
**_Issue:_** 
The `Explore` button on the paths card returns to the Home screen rather than displaying details about the path.

**_Symptoms:_**
The Home screen is displayed instead of path details when the `Explore' button is clicked.

**_Steps to Recreate:_** 
On the Home screen click on the `Show Me the Paths` button and then from the Paths screen click on the `Explore` button on any path card.

**_Resolution:_**

**Comment by kimkwanka** [comment]
Fixed along with changes to Dashboard.
