### ISSUE TITLE
Failure to load favicon.ico (404)

### ISSUE THREAD

**Issue by jdmedlock** [Chingu-cohorts/devgaido#36]
**_Issue Description & Expected Outcome:_** 
A message indicating that favicon.ico could not be loaded is issued to the console log during the initial display of the Home page.

**_Symptoms:_**
On initial display of the Home page the following message is issued in the console log:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**_Steps to Recreate:_** 
From a terminal session start devGaido using the `yarn dev` commend. Next, open a browser session to `http://localhost:8080/dashboard` and open the console log to see the message.

**_Resolution:_** 
Corrected code and added new devGaido icon

**Comment by kimkwanka** [comment]
This was just because we didn't have a favicon yet, now we do (for all kinds of devices).
