### ISSUE TITLE
Page /library  loads at the bottom

### ISSUE THREAD

**Issue by Alexever17** [Chingu-cohorts/devgaido#69]
**_Issue Description & Expected Outcome:_** 
Sometime you land on the bottom of the http://www.devgaido.com/library  page if you go through the pages a lot and look at different courses.

**_Symptoms:_**

**_Steps to Recreate:_** 
Hmm not sure how to recreate, but it happens quite a lot if you switch through a lot of pages

this worked some times
1) visit http://www.devgaido.com/library 
2) go through a categorie to the last page like http://www.devgaido.com/lessons/trygit
3) now hit back all the way until the start page http://www.devgaido.com/
4) go one to the front again to http://www.devgaido.com/library   
you are at the bottom

**_Resolution:_** 
no clue

**Comment by kimkwanka** [comment]
This is caused by React Router V4's default behaviour (not resetting scroll when transitioning between pages) and is fixed in the new branch.
