### ISSUE TITLE
Back button at course pages and others

### ISSUE THREAD

**Issue by Alexever17** [Chingu-cohorts/devgaido#70]
**_Issue Description & Expected Outcome:_** 
It would be nice to have a back button at pages like http://www.devgaido.com/courses/p1xtprereqs and other similar ones because hitting the browser back button feels slow after the fast menu

**Comment by Alexever17** [comment]
Because somebody asked:

It feels very natural to click on the next square to go to the next section. But if you want to go back one step, you would have to use the back button of the browser.

Of course its not necessery, but i think it would prived a better experience if you can instead click on a dedicated squer/button to go back one step

**Comment by jdmedlock** [comment]
Good point. We will explore the addition of a back button.

**Comment by kimkwanka** [comment]
Added a back button in side drawer to new version.
