### ISSUE TITLE
Dashboard / In Progress Page Does Not Reflect Selected Path

### ISSUE THREAD

**Issue by AgedLace** [Chingu-cohorts/devgaido#72]
**_Issue Description & Expected Outcome:_** 
In my first session I had selected "JavaScript" from the Library Page's Dropdown Menu, then selected P1XT Guide and then completed the first 2 Git Lessons.  
Upon logging back into the Dashboard later, the "In Progress" Page said "You haven't started any paths yet."  I returned to the Library Page and drilled back down again.  
[EDIT - I have since found that teeny tiny breadcrumbs menu in the upper left hand corner!]
Next time, I'll bookmark the Lesson I'm on before I logout so that I can get back to that page more efficiently. [Bad foresight on my part!]

**_Symptoms:_**
"In Progress" Page says "You haven't started any paths yet."

**_Steps to Recreate:_** 
Created account.  
Went to Library Page.  
Used Drop Down menu and selected "JavaScript" for my path.  
Selected the P1XT Guide
Completed the first 2 Git courses 
Logged Out
Logged Back into Dashboard
"In Progress Page" says "You haven't started any paths yet."

**_Resolution:_** 
Links to completed classes on "In Progress" page, and a link to the next class in the path.

**Comment by jdmedlock** [comment]
Verified with @AgedLace that this is resolved
