### ISSUE TITLE
Congested Login Popup

### ISSUE THREAD

**Issue by buoyantair** [Chingu-cohorts/devgaido#73]
So yeah this is my first issue here 😊 

**_Issue Description & Expected Outcome:_** 

I checked out the login page/popup and It seems to appear a little congested. 
Check this screenshot out.
![image](https://user-images.githubusercontent.com/5159834/28508173-a26f767c-7056-11e7-939f-217301b963f8.png)

The close button is not only awkwardly placed, the logo also seems pretty large in ratio to the size of the popup.

I've gone into the dev tools and tried to play around, here's what I got, by slightly changing the width to around 400-500 and moving the "x" button around so it's aligned at 10px/10px ratio from top right.

![image](https://user-images.githubusercontent.com/5159834/28508219-035a707c-7057-11e7-8f66-f8aa021c8d5d.png)

I feel like it looks more welcoming to have the width increased and the elements inside (like "x" button) enhanced to match the new size.

**_Symptoms:_**
n/a

**_Steps to Recreate:_** 
- Go to home page
- Click on Login button

**_Resolution:_** 
n/a

**Comment by kimkwanka** [comment]
Added in next release.
