### ISSUE TITLE
UX/UI issues

### ISSUE THREAD

**Issue by reneerich70** [Chingu-cohorts/devgaido#76]
I love this site--looking forward to using it when it's completed!

I navigated through the site in Chrome and Opera and it rendered the same in both browsers on 15 inch laptop. I also entered the site using Chrome on Galaxy S7 edge and Galaxy tablet A 8 inch...
/****Login****/
1. no trouble using Github to login- When I tested the reset password the back arrow and the close (x) at the top of the container moved down to the logo on 15 inch laptop and tablet. It renders quite a bit better on the cell phone.
2. after logging in it flashes the homepage and then goes straight to the dashboard. Maybe once logged in we could stay on the homepage and then be allowed to choose to go to the dashboard.
/*****Home Page****/
1. On the tablet, the images below the fold show up normal in landscape (962 px width) with paragraph text aligned correctly, but are distorted in portrait (600 px width), and on the cell phone. 
2. May want to increase font size of paragraphs to reduce the amount of empty space on the larger devices.
3. Narration: Something is needed that states what type of learning will be delivered above the fold...front-end, development in general, web only, all the above?? The middle paragraph--the last part of the sentence isn't necessary and feels incomplete.(w"...without the hassle") Also, I don't know that the last paragraph on the landing page is really necessary..."Never worry about learning....etc" I think you have enough in the first two paragraphs to draw interest in the site without introducing a negative statement about other sites. 
/****Library****/
I love all the choices!
I like the layout and the distinction of main topics by color using the blue as primary topics. 
General topic areas should be grouped and a header for each section placed above the primary card for each section. For example: Webpage Design and Development--it should be grouped in order of difficult and all the cards that involve html/css/sass should be grouped together and tiered in the best way for learning. 
/****Footer****/
only the disclaimer link works which you probably know, and it navigates to the bottom of the page when clicked.
/****General ****/
1. I know this is still a work in progress. Are you considering adding in maybe asking the user questions involving what they would like to learn and then point them in that direction on your site? 
2. Are you planning to offer a getting started page so learners can get information on what direction they may need to go based on their goals?

**Comment by jdmedlock** [comment]
Thank you for the great feedback!
1. Responsiveness is currently an issue we are working on. 
2. Defaulting to the dashboard was a design decision. The feeling at the time was that once authenticated the user would prefer to go to the dashboard to resume lessons in progress or to search for new learning. This doesn't mean this can't be changed. We will consider adding a navbar option to return to the Landing Page. 
3. See number 1 above. We will definitely be working on making the app more responsive.
4. We'll look into this. We have also considered adding a thumbnail of the lesson to the lesson card to provide another visual clue to the content. We want to make the app interesting and more visually pleasing, but we don't want to fall into the trap of adding things just to fill up space. We will look at how to du this in a way that adds value at the same time though.
5. Good ideas! We'll review at our next dev team meeting
6 & 7. These are things we considered early on in the project, but elected to defer until a later sprint. We wanted to first establish the fundamentals, but creating a "wizard" approach to provide a higher level of guidance (maybe even AI) is a great suggestion.

**Comment by jdmedlock** [comment]
Related to #68

**Comment by jdmedlock** [comment]
5. In this week's next MVP #1 release a new type icon will be added to lessons to provide a visual clue as to whether the content is delivered through reading, video, etc. Also changing the tone of the Landing page text to be positive rather than negative. Other items you suggested in this bullet are still being reviewed.
