### ISSUE TITLE
Lesson Complete/Not Complete Reset

### ISSUE THREAD

**Issue by MartinWoodj** [Chingu-cohorts/devgaido#78]
Once the lesson complete button on the lesson page is selected there is no way to unselect it or reset it. I would also suggest this be an option to unselect on the dashboard page as well.

**Comment by kimkwanka** [comment]
An "uncomplete" lesson button will be added in the version.

**Comment by jdmedlock** [comment]
This functionality has been added to the next release.

**Comment by jdmedlock** [comment]
This functionality was included in todays promotion of the new release to Production.
