### ISSUE TITLE
Remove Tracked Path From Progress

### ISSUE THREAD

**Issue by MartinWoodj** [Chingu-cohorts/devgaido#79]
Once you select a path to begin by clicking the Start Path then you are unable to remove starting that path if you were to change your mind. Also if you start a path then navigate to another path and start that one then both of those paths should show in the dashboard area as being in progress.

**Comment by kimkwanka** [comment]
This behaviour is completely changed in the next version. In that version you will no longer need to click "Start Path" to commence working. And can swap freely between all paths.
