### ISSUE TITLE
Do not animate large portions of DOM

### ISSUE THREAD

**Issue by buoyantair** [Chingu-cohorts/devgaido#80]
**_Issue Description & Expected Outcome:_** 
When I first looked at the menu and tried to change pages, the application kind of seemed slow because you're trying to animate and translate the whole page to left or right to get to the destination page. This could be problematic sometimes and can cause the website to become slow. Think about the library page for example, it's filled with a lot of elements, I've lazy loaded every path/course. If I am to click on dashboard or to go to my profile, the whole page is being animated to the side. This could cause lag and in older browsers I believe this would make them crash. 

Maybe we should use something more simple like having a simple loading circle covering the whole page atop and then remove and load the elements behind the cover, like replacing the contents of a container element, so we don't put a lot of pressure on GPU rendering the translation of the whole page.

**_Symptoms:_**
Transitioning large portions of DOM can cause lag. 
**_Steps to Recreate:_** 
- Login and go to library
- wait for everything to load
- repeatedly change pages from dashboard to library to profile and/or vice versa
**_Resolution:_**

**Comment by jdmedlock** [comment]
Resolved by change in loading strategy to not load everything at once. We will keep the DOM advice in mind.
