### ISSUE TITLE
Last Lesson in a Milestone of a Path is Cut Off

### ISSUE THREAD

**Issue by AgedLace** [Chingu-cohorts/devgaido#84]
**_Issue Description & Expected Outcome:_** 
I'm working through the P1XT Guide.  When on the Path Page, the last lesson in a milestone is being cut off.  
**_Symptoms:_**
I will past the image in the slack channel since I can't figure out how to post them here.  :(

**_Steps to Recreate:_** 
Go to a Path page; open a milestone ... go down to the last lesson in that milestone.  

**_Resolution:_** 
I don't know ?

**Comment by jdmedlock** [comment]
Fixed in latest release promoted to Production on 7/27/2017.
