### ISSUE TITLE
/library feels unwieldy

### ISSUE THREAD

**Issue by Sandbin42** [Chingu-cohorts/devgaido#88]
This may be similar to issue **#71 Clarification of /library page**

When I go to /library it feels like a lot to have all paths and lessons auto-populated all at once. This will only get more overwhelming as more paths and lessons are added.

Suggestion: Maybe start by showing only paths and having an option to switch? This might complement the already great topic selection and search, and give the user more control :)

**Comment by jdmedlock** [comment]
Explore adding an additional drop down to filter by content type. For example, All, Path, or Lesson

**Comment by jdmedlock** [comment]
Added a filtering option to display only paths or lessons to add clarity to what type of content is being displayed.

**Comment by kimkwanka** [comment]
Added tabs to live version.
