### ISSUE TITLE
"Ghost" Links

### ISSUE THREAD

**Issue by buoyantair** [Chingu-cohorts/devgaido#92]
**_Issue Description & Expected Outcome:_** 
The new drop down feature for paths is a bit buggy. Some links which are not shown are getting "hover" triggers on the mouse. 

[Update]
This seems to be happening on pretty much all the drop down feature headings, just try to hover the mouse in between the gutters and you'll find your mouse changed to a pointer and pointing to the first link in that drop down feature if you look at your browser's bottom left/right prompts 

**_Symptoms:_**
Likely because of how the child elements of the drop down feature are hidden.
**_Steps to Recreate:_** 
- Go to any path page, and scroll down to this point 
![image](https://user-images.githubusercontent.com/5159834/28741724-979cca78-743a-11e7-940e-db1a30350a74.png)

- Now hover your mouse _just_ below the "PATH COMPLETION" element, about 40-50px away. 
- You'll notice that your mouse turns to a pointer and browser shows an indication to where the link is pointed to in the bottom left/right
![image](https://user-images.githubusercontent.com/5159834/28741740-199a3542-743b-11e7-96df-709ea421de41.png)

This issue is spotted on Firefox 54.0.1 (64 bit)

**_Resolution:_** 

**_Suggestions:_** Turns out you guys are trying to change the opacity of the contents along with max-height, which won't really fix this issue. Using a `display: none` on the class `.collapsed` will stop the browser from "sneaky" rendering the elements. Additionally, when I added display:none to the `.collapsed` class, all the toggle headers don't seem to have any kind of padding/margin, and that resulted in all the elements packed together :/ 
![image](https://user-images.githubusercontent.com/5159834/28741794-266c3f6c-743c-11e7-8766-0d213d943aa3.png)

![image](https://user-images.githubusercontent.com/5159834/28741796-34c60e1c-743c-11e7-8a0b-601e10d0ae9f.png)

**Comment by buoyantair** [comment]
Corrected Firefox version

**Comment by kimkwanka** [comment]
This issue will be fixed in the next version. Like you realized, setting display to none doesn't quite do the trick here since the display property is non animate-able and comes with other issues. Adding pointer-events: none instead does prevent the unwanted behavior though and fixes this bug.

**Comment by buoyantair** [comment]
@kimkwanka oooo on the go! I don't know there's a `pointer-events` thing! 💃

**Comment by kimkwanka** [comment]
Fixed in live version.
