### ISSUE TITLE
Feature Request - Toggle Ability to Show / Hide Finished Paths / Lessons on Library Page

### ISSUE THREAD

**Issue by AgedLace** [Chingu-cohorts/devgaido#95]
**_Issue Description & Expected Outcome:_** 
First, I LOVE the new changes ... I think they're an awesome improvement.  This feature request comes from the perspective that as paths and lessons get added, there are going to be a LOT of items on the new library pages.  Once people complete a substantial amount of paths and/or lessons, it might help to be able to show/hide both hose paths or classes which the user has completed, as well as show/hide those paths / lessons they have completed.   

**_Symptoms:_**
Right now, the new library pages list all paths  / lessons ... both those completed, as well as uncompleted.  
What if the user wants to search through just those paths / lessons they have completed?
What if the user wants to search only those paths / lessons which they have not yet completed?

**_Steps to Recreate:_** 

**_Resolution:_** 
Create search options on the library pages to search completed; and a search for  uncompleted, as well as keep the current view of showing everything like it does now.

**Comment by jdmedlock** [comment]
Resolve in latest Production release
